# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a base image that includes bun
FROM oven/bun:latest

# Set the working directory inside the container
WORKDIR /app

# Copy package.json, tsconfig.json, and index.ts to the working directory
COPY package.json tsconfig.json index.ts ./

# Copy any additional files needed for the project
COPY utils ./utils

# Install dependencies using bun
RUN bun install

# Set the default command to run when the container starts
CMD ["bun", "run", "index.ts"]
